Admeme Invisiwalls.
Guloveos/arc-station-14 pull request #75
Opened 2024-09-29 02:40 UTC by Hobbitmax

## About the PR

Added a Admeme Invisible wall. which will not despawn. 
## EVER.
not even god can destroy it. so be careful but have fun.

## Why / Balance

## Technical details

FBI wanted it. i made it. Yell at them if its unbalanced.

## Media

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-09-29 03:30 UTC, TheDoctor1977 requested changes
this _needs_ a way to be removed with admin tooling
see about making it show with a visibility toggle - maybe show spawns?

2024-09-29 16:23 UTC, Hobbitmax commented
> this _needs_ a way to be removed with admin tooling see about making it show with a visibility toggle - maybe show spawns?

i figured out how to make it show a X when showspawns are on. this was not easy. this was painful. also i added more lines to the merc drobe and ERP drobe for when you buy something at FBIs request.

2024-09-29 17:52 UTC, TheDoctor1977 requested changes

2024-09-29 17:52 UTC, TheDoctor1977 commented on Resources/Locale/en-US/advertisements/vending/merc.ftl
> +thankyou-mercdrobe-3 = Dont forget your orders, Lads!
minor spelling error i'll kill you for this
```suggestion
thankyou-mercdrobe-3 = Don't forget your orders, lads!
```

2024-09-30 21:48 UTC, TheDoctor1977 approved these changes

2024-09-30 21:49 UTC, merged